var time_range_to_reconstruct_fromSilder = document.getElementById(time_range_to_reconstruct_fromSilder);
var time_range_to_reconstruct_toSilder = document.getElementById(time_range_to_reconstruct_toSilder);
var time_range_to_reconstruct_fromInput = document.getElementById(time_range_to_reconstruct_fromInput);
var time_range_to_reconstruct_toInput = document.getElementById(time_range_to_reconstruct_toInput);
fillSlider(time_range_to_reconstruct_fromSilder, time_range_to_reconstruct_toSilder, #C6C6C6, #25daa5, time_range_to_reconstruct_toSilder);
setToggleAccessible(time_range_to_reconstruct_toSilder);
time_range_to_reconstruct_fromSilder.oninput = () => controlFromSlider(time_range_to_reconstruct_fromSilder, time_range_to_reconstruct_toSilder, time_range_to_reconstruct_fromInput);
time_range_to_reconstruct_toSilder.oninput = () => controlToSlider(time_range_to_reconstruct_fromSilder, time_range_to_reconstruct_toSilder, time_range_to_reconstruct_toInput);
time_range_to_reconstruct_fromInput.onchange = () => controlFromInput(time_range_to_reconstruct_fromSilder, time_range_to_reconstruct_fromInput, time_range_to_reconstruct_toInput, time_range_to_reconstruct_toSilder);
time_range_to_reconstruct_toInput.onchange = () => controlToInput(time_range_to_reconstruct_toSilder, time_range_to_reconstruct_fromInput, time_range_to_reconstruct_toInput, time_range_to_reconstruct_toSilder);
var time_reference_fromSilder = document.getElementById(time_reference_fromSilder);
var time_reference_toSilder = document.getElementById(time_reference_toSilder);
var time_reference_fromInput = document.getElementById(time_reference_fromInput);
var time_reference_toInput = document.getElementById(time_reference_toInput);
fillSlider(time_reference_fromSilder, time_reference_toSilder, #C6C6C6, #25daa5, time_reference_toSilder);
setToggleAccessible(time_reference_toSilder);
time_reference_fromSilder.oninput = () => controlFromSlider(time_reference_fromSilder, time_reference_toSilder, time_reference_fromInput);
time_reference_toSilder.oninput = () => controlToSlider(time_reference_fromSilder, time_reference_toSilder, time_reference_toInput);
time_reference_fromInput.onchange = () => controlFromInput(time_reference_fromSilder, time_reference_fromInput, time_reference_toInput, time_reference_toSilder);
time_reference_toInput.onchange = () => controlToInput(time_reference_toSilder, time_reference_fromInput, time_reference_toInput, time_reference_toSilder);
var time_model_interval_fromSilder = document.getElementById(time_model_interval_fromSilder);
var time_model_interval_toSilder = document.getElementById(time_model_interval_toSilder);
var time_model_interval_fromInput = document.getElementById(time_model_interval_fromInput);
var time_model_interval_toInput = document.getElementById(time_model_interval_toInput);
fillSlider(time_model_interval_fromSilder, time_model_interval_toSilder, #C6C6C6, #25daa5, time_model_interval_toSilder);
setToggleAccessible(time_model_interval_toSilder);
time_model_interval_fromSilder.oninput = () => controlFromSlider(time_model_interval_fromSilder, time_model_interval_toSilder, time_model_interval_fromInput);
time_model_interval_toSilder.oninput = () => controlToSlider(time_model_interval_fromSilder, time_model_interval_toSilder, time_model_interval_toInput);
time_model_interval_fromInput.onchange = () => controlFromInput(time_model_interval_fromSilder, time_model_interval_fromInput, time_model_interval_toInput, time_model_interval_toSilder);
time_model_interval_toInput.onchange = () => controlToInput(time_model_interval_toSilder, time_model_interval_fromInput, time_model_interval_toInput, time_model_interval_toSilder);
var proxy_resoltion_fromSilder = document.getElementById(proxy_resoltion_fromSilder);
var proxy_resoltion_toSilder = document.getElementById(proxy_resoltion_toSilder);
var proxy_resoltion_fromInput = document.getElementById(proxy_resoltion_fromInput);
var proxy_resoltion_toInput = document.getElementById(proxy_resoltion_toInput);
fillSlider(proxy_resoltion_fromSilder, proxy_resoltion_toSilder, #C6C6C6, #25daa5, proxy_resoltion_toSilder);
setToggleAccessible(proxy_resoltion_toSilder);
proxy_resoltion_fromSilder.oninput = () => controlFromSlider(proxy_resoltion_fromSilder, proxy_resoltion_toSilder, proxy_resoltion_fromInput);
proxy_resoltion_toSilder.oninput = () => controlToSlider(proxy_resoltion_fromSilder, proxy_resoltion_toSilder, proxy_resoltion_toInput);
proxy_resoltion_fromInput.onchange = () => controlFromInput(proxy_resoltion_fromSilder, proxy_resoltion_fromInput, proxy_resoltion_toInput, proxy_resoltion_toSilder);
proxy_resoltion_toInput.onchange = () => controlToInput(proxy_resoltion_toSilder, proxy_resoltion_fromInput, proxy_resoltion_toInput, proxy_resoltion_toSilder);
var proxy_percent_fromSilder = document.getElementById(proxy_percent_fromSilder);
var proxy_percent_toSilder = document.getElementById(proxy_percent_toSilder);
var proxy_percent_fromInput = document.getElementById(proxy_percent_fromInput);
var proxy_percent_toInput = document.getElementById(proxy_percent_toInput);
fillSlider(proxy_percent_fromSilder, proxy_percent_toSilder, #C6C6C6, #25daa5, proxy_percent_toSilder);
setToggleAccessible(proxy_percent_toSilder);
proxy_percent_fromSilder.oninput = () => controlFromSlider(proxy_percent_fromSilder, proxy_percent_toSilder, proxy_percent_fromInput);
proxy_percent_toSilder.oninput = () => controlToSlider(proxy_percent_fromSilder, proxy_percent_toSilder, proxy_percent_toInput);
proxy_percent_fromInput.onchange = () => controlFromInput(proxy_percent_fromSilder, proxy_percent_fromInput, proxy_percent_toInput, proxy_percent_toSilder);
proxy_percent_toInput.onchange = () => controlToInput(proxy_percent_toSilder, proxy_percent_fromInput, proxy_percent_toInput, proxy_percent_toSilder);
var geo_proxy_lon_fromSilder = document.getElementById(geo_proxy_lon_fromSilder);
var geo_proxy_lon_toSilder = document.getElementById(geo_proxy_lon_toSilder);
var geo_proxy_lon_fromInput = document.getElementById(geo_proxy_lon_fromInput);
var geo_proxy_lon_toInput = document.getElementById(geo_proxy_lon_toInput);
fillSlider(geo_proxy_lon_fromSilder, geo_proxy_lon_toSilder, #C6C6C6, #25daa5, geo_proxy_lon_toSilder);
setToggleAccessible(geo_proxy_lon_toSilder);
geo_proxy_lon_fromSilder.oninput = () => controlFromSlider(geo_proxy_lon_fromSilder, geo_proxy_lon_toSilder, geo_proxy_lon_fromInput);
geo_proxy_lon_toSilder.oninput = () => controlToSlider(geo_proxy_lon_fromSilder, geo_proxy_lon_toSilder, geo_proxy_lon_toInput);
geo_proxy_lon_fromInput.onchange = () => controlFromInput(geo_proxy_lon_fromSilder, geo_proxy_lon_fromInput, geo_proxy_lon_toInput, geo_proxy_lon_toSilder);
geo_proxy_lon_toInput.onchange = () => controlToInput(geo_proxy_lon_toSilder, geo_proxy_lon_fromInput, geo_proxy_lon_toInput, geo_proxy_lon_toSilder);
