PREFIX le: <http://linked.earth/ontology#>

    SELECT ?values
    WHERE {
        ?ds a le:Dataset .
    	?ds le:includesPaleoData ?data .
        ?data le:foundInMeasurementTable ?table .
        ?table le:includesVariable ?var .
	?var le:hasVariableID ?hasVariableID .
		FILTER (regex(?hasVariableID, "Asia_163") || regex(?hasVariableID, "Asia_022")) .
	?var le:hasValues ?values .
}
LIMIT 100
