/**
 * LiPD Data Service
 * Handles generation and upload of LiPD pickle files for LMR reconstructions
 */

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const { Octokit } = require('@octokit/rest');

/**
 * Generate LiPD pickle from user query parameters
 * This function will query the LiPDverse based on user filters,
 * download selected LiPD files, and convert to pickle format
 *
 * @param {Object} queryParams - User data selection parameters
 * @param {string} queryParams.compilation - Compilation name (e.g., 'PAGES2kv2')
 * @param {Array} queryParams.coords - [lat_min, lat_max, lon_min, lon_max]
 * @param {Array} queryParams.archiveTypes - Archive type filters (optional)
 * @param {string} queryParams.variableName - Variable name filter (optional)
 * @param {string} uniqueID - Unique reconstruction identifier
 * @returns {Promise<Buffer>} - LiPD pickle file content as Buffer
 */
async function generateLipdPickle(queryParams, uniqueID) {
  console.log('Generating LiPD pickle for reconstruction:', uniqueID);
  console.log('Query parameters:', JSON.stringify(queryParams, null, 2));

  // Check if this is an archived compilation
  const userReconDir = path.join(__dirname, '..', 'userRecons', `${uniqueID}_LMR`);
  const archivedCompPath = path.join(userReconDir, 'archivedComp.json');

  if (fs.existsSync(archivedCompPath)) {
    console.log('Archived compilation detected, using downloadCompilation approach...');
    const archiveInfo = JSON.parse(fs.readFileSync(archivedCompPath, 'utf8'));
    console.log('Compilation:', archiveInfo.compilation, 'Version:', archiveInfo.version);

    // Download the pickle directly from lipdverse
    const baseURL = `https://lipdverse.org/${archiveInfo.compilation}/${archiveInfo.version}/${archiveInfo.compilation}${archiveInfo.version}`;
    const pickleUrl = `${baseURL}.pkl`;

    // Create temp directory for download
    const tempDir = path.join(__dirname, '..', 'temp', uniqueID);
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }

    const pickleOutputPath = path.join(tempDir, 'lipd_data.pkl');
    console.log('Downloading pickle from:', pickleUrl);

    await new Promise((resolve, reject) => {
      const curlProcess = spawn('curl', ['-L', pickleUrl, '-o', pickleOutputPath]);

      curlProcess.stdout.on('data', (data) => {
        console.log('curl output:', data.toString());
      });

      curlProcess.stderr.on('data', (data) => {
        console.log('curl progress:', data.toString());
      });

      curlProcess.on('close', (code) => {
        if (code !== 0) {
          reject(new Error(`curl download failed with code ${code}`));
        } else {
          console.log('Archived compilation pickle downloaded successfully');
          resolve();
        }
      });
    });

    // Read and return the pickle file
    const pickleData = fs.readFileSync(pickleOutputPath);
    console.log(`Downloaded pickle file size: ${pickleData.length} bytes`);
    return pickleData;
  }

  // Otherwise, use the filtering approach
  console.log('Using database filtering approach...');

  // Create temp directory for this reconstruction
  const tempDir = path.join(__dirname, '..', 'temp', uniqueID);
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true });
  }

  // Write query parameters to JSON file for R script
  const queryParamsPath = path.join(tempDir, 'query_params.json');
  fs.writeFileSync(queryParamsPath, JSON.stringify(queryParams, null, 2));

  // Run lipdGenerator container: queries lipdverse, downloads .lpd files, creates pickles
  console.log('Running lipdGenerator container...');
  await new Promise((resolve, reject) => {
    const dockerProcess = spawn('docker', [
      'run', '--rm',
      '-v', `${queryParamsPath}:/query_params.json:ro`,
      '-v', `${tempDir}:/output`,
      'davidedge/lipd_webapps:lipdGenerator',
      '/query_params.json', '/output', 'all'
    ]);

    dockerProcess.stdout.on('data', (data) => {
      console.log('lipdGenerator output:', data.toString());
    });

    dockerProcess.stderr.on('data', (data) => {
      console.error('lipdGenerator stderr:', data.toString());
    });

    dockerProcess.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`lipdGenerator container failed with code ${code}`));
      } else {
        console.log('lipdGenerator completed successfully');
        resolve();
      }
    });
  });

  // Read the generated pickle file (lipdPickler writes lipd.pkl)
  const pickleOutputPath = path.join(tempDir, 'lipd.pkl');
  if (!fs.existsSync(pickleOutputPath)) {
    throw new Error('lipd.pkl was not generated by lipdPickler container');
  }

  const pickleData = fs.readFileSync(pickleOutputPath);
  console.log(`Generated pickle file size: ${pickleData.length} bytes`);

  return pickleData;
}

/**
 * Upload LiPD pickle to user's GitHub repository
 *
 * @param {string} token - GitHub OAuth token
 * @param {string} owner - Repository owner (username)
 * @param {string} repo - Repository name
 * @param {Buffer} pickleData - LiPD pickle file content
 * @returns {Promise<string>} - Raw GitHub URL to pickle file
 */
async function uploadLipdToRepo(token, owner, repo, pickleData) {
  console.log(`Uploading LiPD pickle to ${owner}/${repo}...`);

  const octokit = new Octokit({ auth: token });
  const filePath = 'data/lipd_data.pkl';

  try {
    // Create blob for the pickle file
    const { data: blob } = await octokit.rest.git.createBlob({
      owner,
      repo,
      content: pickleData.toString('base64'),
      encoding: 'base64'
    });

    // Get current main branch reference
    const { data: ref } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: 'heads/main'
    });
    const currentCommitSha = ref.object.sha;

    // Get current commit tree
    const { data: currentCommit } = await octokit.rest.git.getCommit({
      owner,
      repo,
      commit_sha: currentCommitSha
    });
    const currentTreeSha = currentCommit.tree.sha;

    // Create new tree with the pickle file
    const { data: newTree } = await octokit.rest.git.createTree({
      owner,
      repo,
      base_tree: currentTreeSha,
      tree: [
        {
          path: filePath,
          mode: '100644',
          type: 'blob',
          sha: blob.sha
        }
      ]
    });

    // Create new commit
    const { data: newCommit } = await octokit.rest.git.createCommit({
      owner,
      repo,
      message: 'Add LiPD proxy data for reconstruction',
      tree: newTree.sha,
      parents: [currentCommitSha]
    });

    // Update main branch reference
    await octokit.rest.git.updateRef({
      owner,
      repo,
      ref: 'heads/main',
      sha: newCommit.sha
    });

    // Construct raw GitHub URL
    const rawUrl = `https://github.com/${owner}/${repo}/raw/main/${filePath}`;
    console.log('LiPD pickle uploaded successfully:', rawUrl);

    return rawUrl;
  } catch (error) {
    console.error('Error uploading LiPD pickle:', error);
    throw new Error(`Failed to upload LiPD pickle: ${error.message}`);
  }
}

/**
 * Generate and upload LiPD pickle in one step
 *
 * @param {Object} queryParams - User data selection parameters
 * @param {string} uniqueID - Unique reconstruction identifier
 * @param {string} token - GitHub OAuth token
 * @param {string} owner - Repository owner
 * @param {string} repo - Repository name
 * @returns {Promise<string>} - Raw GitHub URL to pickle file
 */
async function generateAndUploadLipdPickle(queryParams, uniqueID, token, owner, repo) {
  try {
    // Generate pickle
    const pickleData = await generateLipdPickle(queryParams, uniqueID);

    // Upload to GitHub
    const pickleUrl = await uploadLipdToRepo(token, owner, repo, pickleData);

    // Clean up temp directory
    const tempDir = path.join(__dirname, '..', 'temp', uniqueID);
    if (fs.existsSync(tempDir)) {
      fs.rmSync(tempDir, { recursive: true, force: true });
      console.log('Cleaned up temp directory');
    }

    return pickleUrl;
  } catch (error) {
    console.error('Error in generateAndUploadLipdPickle:', error);
    throw error;
  }
}

module.exports = {
  generateLipdPickle,
  uploadLipdToRepo,
  generateAndUploadLipdPickle
};
