#!/bin/bash

# Generate Visualizations Script
# Creates interactive visualizations for Holocene DA reconstructions

set -e

echo "========================================"
echo "Generating Visualizations"
echo "========================================"

DOCKER_IMAGE="${DOCKER_IMAGE:-davidedge/lipd_webapps:holocene_da_viz}"
RESULTS_DIR="${RESULTS_DIR:-results}"

echo "Docker Image: $DOCKER_IMAGE"
echo "Results Directory: $RESULTS_DIR"

# Ensure visualization directory exists
mkdir -p "$RESULTS_DIR/viz"

# Check if reconstruction results exist
if [ ! -d "$RESULTS_DIR/data" ]; then
  echo "ERROR: Reconstruction data not found at $RESULTS_DIR/data"
  exit 1
fi

# Pull the Docker image
echo ""
echo "Pulling Docker image: $DOCKER_IMAGE"
docker pull "$DOCKER_IMAGE"

# Generate visualizations
echo ""
echo "Generating interactive visualizations..."
echo ""

# Run visualization container
docker run --rm \
  -v "$(pwd)/$RESULTS_DIR:/app/results:rw" \
  "$DOCKER_IMAGE" \
  /bin/bash -c "cd /app && python visualize.py /app/results/data /app/results/viz" \
  | tee "$RESULTS_DIR/logs/visualization.log"

# Create index.html if it doesn't exist
if [ ! -f "$RESULTS_DIR/viz/index.html" ]; then
  echo "Creating index.html..."
  cat > "$RESULTS_DIR/viz/index.html" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PReSto Holocene DA Reconstruction Results</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    h1 { color: #333; }
    .visualization {
      background: white;
      padding: 20px;
      margin: 20px 0;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    img {
      max-width: 100%;
      height: auto;
    }
  </style>
</head>
<body>
  <h1>PReSto Holocene DA Reconstruction Results</h1>
  <p><strong>Reconstruction ID:</strong> $UNIQUE_ID</p>
  <p><strong>Generated:</strong> $(date)</p>

  <div class="visualization">
    <h2>Reconstruction Visualizations</h2>
EOF

  # List all PNG files in viz directory
  for img in "$RESULTS_DIR/viz"/*.png; do
    if [ -f "$img" ]; then
      BASENAME=$(basename "$img")
      echo "    <h3>${BASENAME%.png}</h3>" >> "$RESULTS_DIR/viz/index.html"
      echo "    <img src=\"$BASENAME\" alt=\"$BASENAME\">" >> "$RESULTS_DIR/viz/index.html"
    fi
  done

  cat >> "$RESULTS_DIR/viz/index.html" <<EOF
  </div>

  <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center;">
    <p>Generated by <a href="https://paleopresto.com/">PReSto</a></p>
  </footer>
</body>
</html>
EOF
fi

echo ""
echo "========================================"
echo "Visualizations Complete"
echo "========================================"

# List visualization files
echo "Visualization files:"
find "$RESULTS_DIR/viz" -type f | sort
