#===================================
# SETTINGS for running the LMR code.
# Configs tested with cfr (v.2024.4.17) and xarray<=2024.02
# https://github.com/fzhu2e/cfr
#===================================

recon:
  output_indices:
    value: [gm, nhm, shm]
    default: [gm, nhm, shm]
    limits: null
    options: [gm, nhm, shm]
    precision: null
    long_name: output climate indices
    description: Output climate indices in addition to the tas field (gm=global mean, nhm=NH mean, shm=SH mean)
    data_type: list
    complexity: standard
    URL: null

  period:
    value: [0, 2000]
    default: [0, 2000]
    limits: [0, 2000]
    options: null
    precision: 1
    long_name: reconstruction period
    description: Reconstruction period, usually within [0, 2000]
    data_type: range
    complexity: standard
    URL: null

  seeds:
    value: [1, 2, 3]
    default: [1, 2, 3]
    limits: null
    options: null
    precision: null
    long_name: Monte Carlo random seeds
    description: The random seed for each Monte-Carlo iterations; the larger the better, somewhere 10-20 is good for LMR cases
    data_type: list
    complexity: standard
    URL: null

  vars:
    value: [tas]
    default: [tas]
    limits: null
    options: [tas]
    precision: null
    long_name: variables to reconstruct
    description: The field to reconstruct, always tas for our application
    data_type: list
    complexity: standard
    URL: null

  loc_rad:
    value: 25000
    default: 25000
    limits: [1000, 100000]
    options: null
    precision: 1000
    long_name: localization radius
    description: The localization radius
    data_type: numeric
    complexity: standard
    URL: null

  sampling_mode:
    value: fixed
    default: fixed
    limits: null
    options: [fixed]
    precision: null
    long_name: temporal sampling mode
    description: The way of temporal sampling for the prior, no need to modify for LMR
    data_type: character
    complexity: experimental
    URL: null

  timescale:
    value: 1
    default: 1
    limits: [1, 100]
    options: null
    precision: 1
    long_name: temporal resolution
    description: Annual resolution is assumed for LMR reconstructions, other numbers not tested
    data_type: numeric
    complexity: experimental
    URL: null

  output_full_ens:
    value: false
    default: false
    limits: null
    options: [true, false]
    precision: null
    long_name: output full ensemble
    description: If true, cfr will output the full ensemble for the reconstruction field in shape (n_time, n_ens x n_MC, n_lat, n_lon)
    data_type: boolean
    complexity: advanced
    URL: null

  save_dirpath:
    value: ./recons/test-run-da-cfg
    default: ./recons/test-run-da-cfg
    limits: null
    options: null
    precision: null
    long_name: save directory path
    description: The path to store the reconstruction results
    data_type: free-form
    complexity: standard
    URL: null

prior:
  annualize_months:
    value: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    default: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    limits: null
    options: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, -12, -11, -10, -9]
    precision: null
    long_name: seasonality of reconstruction
    description: The seasonality of the reconstruction, the below means calendar year annual reconstruction. Users may set [-12, 1, 2] to reconstruct the winter or [6, 7, 8] to reconstruct the summer or other arbitrary combinations
    data_type: list
    complexity: standard
    URL: null

  anom_period:
    value: [850, 1850]
    default: [850, 1850]
    limits: [0, 2000]
    options: null
    precision: 1
    long_name: prior anomaly period
    description: The period to calculate the anomaly of the prior
    data_type: range
    complexity: standard
    URL: null

  regrid_nlat:
    value: 42
    default: 42
    limits: [10, 180]
    options: null
    precision: 1
    long_name: regridded latitude points
    description: The resolution of the regridded prior - this step is optional and removing them will skip the step
    data_type: numeric
    complexity: advanced
    URL: null

  regrid_nlon:
    value: 63
    default: 63
    limits: [10, 360]
    options: null
    precision: 1
    long_name: regridded longitude points
    description: The resolution of the regridded prior - this step is optional and removing them will skip the step
    data_type: numeric
    complexity: advanced
    URL: null

  path:
    value: null
    default: null
    limits: null
    options: null
    precision: null
    long_name: prior dataset paths
    description: The below part is specific to the prior datasets and most of them should be configured by us, not the users; users may select dataset to use though
    data_type: free-form
    complexity: experimental
    URL: null

  lat_name:
    value: lat
    default: lat
    limits: null
    options: null
    precision: null
    long_name: prior latitude coordinate name
    description: The coordinate name in the prior dataset
    data_type: free-form
    complexity: experimental
    URL: null

  lon_name:
    value: lon
    default: lon
    limits: null
    options: null
    precision: null
    long_name: prior longitude coordinate name
    description: The coordinate name in the prior dataset
    data_type: free-form
    complexity: experimental
    URL: null

  time_name:
    value: time
    default: time
    limits: null
    options: null
    precision: null
    long_name: prior time coordinate name
    description: The coordinate name in the prior dataset
    data_type: free-form
    complexity: experimental
    URL: null

  trim_prior:
    value: true
    default: true
    limits: null
    options: [true, false]
    precision: null
    long_name: trim prior
    description: Not used in LMR applications
    data_type: boolean
    complexity: experimental
    URL: null

proxy:
  db_path:
    value: PAGES2kv2
    default: PAGES2kv2
    limits: null
    options: [PAGES2kv2]
    precision: null
    long_name: proxy database
    description: The nickname of the loaded proxy database fetch from the cloud, full URL 'PAGES2kv2':'https://github.com/fzhu2e/cfr-data/raw/main/pages2kv2.json'
    data_type: character
    complexity: standard
    URL: https://github.com/fzhu2e/cfr-data/raw/main/pages2kv2.json

  assim_frac:
    value: 0.75
    default: 0.75
    limits: [0.1, 1.0]
    options: null
    precision: 0.01
    long_name: fraction of proxies to assimilate
    description: The fraction of proxies to assimilate during each Monte-Carlo iteration
    data_type: numeric
    complexity: standard
    URL: null

  nens:
    value: 100
    default: 100
    limits: [10, 1000]
    options: null
    precision: 1
    long_name: ensemble size
    description: Ensemble size for the prior, the larger the better, 100 is usually a good default
    data_type: numeric
    complexity: standard
    URL: null

  filter_proxydb_kwargs:
    value: null
    default: null
    limits: null
    options: null
    precision: null
    long_name: proxy database filter arguments
    description: This part is related to the selection of proxies to assimilate, users may specify only archive names or specific "archive.proxy", e.g., coral.d18O, tree.TRW
    data_type: free-form
    complexity: experimental
    URL: null

  filter_proxydb_args:
    value: []
    default: []
    limits: null
    options: null
    precision: null
    long_name: proxy database filter arguments list
    description: Do not change this
    data_type: list
    complexity: experimental
    URL: null

  annualize_proxydb_ptypes:
    value: [coral]
    default: [coral]
    limits: null
    options: [coral]
    precision: null
    long_name: proxy types to annualize
    description: This step aims to annualize specific proxy data with monthly resolution, and only coral requires this step
    data_type: list
    complexity: experimental
    URL: null

  annualize_proxydb_months:
    value: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    default: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    limits: null
    options: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    precision: null
    long_name: months for proxy annualization
    description: This step aims to annualize specific proxy data with monthly resolution, and only coral requires this step
    data_type: list
    complexity: experimental
    URL: null

  nobs_lb:
    value: 25
    default: 25
    limits: [1, 100]
    options: null
    precision: 1
    long_name: minimum observations lower bound
    description: Minimum number of observations required
    data_type: numeric
    complexity: advanced
    URL: null

  allownan:
    value: false
    default: false
    limits: null
    options: [true, false]
    precision: null
    long_name: allow NaN values
    description: For tas reconstruction, there should not be any NaNs in the output; if the prior has NaNs (e.g., SST field), this should be turned on
    data_type: boolean
    complexity: experimental
    URL: null

model:
  obs_path:
    value: null
    default: null
    limits: null
    options: null
    precision: null
    long_name: observations dataset paths
    description: The below part is specific to the loaded instrumental observations and most of them should be configured by us, not the users; users may select dataset to use though
    data_type: free-form
    complexity: experimental
    URL: null

  obs_rename_dict:
    value: null
    default: null
    limits: null
    options: null
    precision: null
    long_name: observations variable renaming
    description: Rename dictionary for observation variables
    data_type: free-form
    complexity: experimental
    URL: null

  obs_lat_name:
    value: lat
    default: lat
    limits: null
    options: null
    precision: null
    long_name: observations latitude coordinate name
    description: The coord name in the loaded obs data
    data_type: free-form
    complexity: experimental
    URL: null

  obs_lon_name:
    value: lon
    default: lon
    limits: null
    options: null
    precision: null
    long_name: observations longitude coordinate name
    description: The coord name in the loaded obs data
    data_type: free-form
    complexity: experimental
    URL: null

  obs_time_name:
    value: time
    default: time
    limits: null
    options: null
    precision: null
    long_name: observations time coordinate name
    description: The coord name in the loaded obs data
    data_type: free-form
    complexity: experimental
    URL: null

  obs_anom_period:
    value: [1951, 1980]
    default: [1951, 1980]
    limits: [1800, 2000]
    options: null
    precision: 1
    long_name: observations anomaly period
    description: The period to calculate anomaly of the instrumental observations
    data_type: range
    complexity: standard
    URL: null

psm:
  ptype_clim_dict:
    value: null
    default: null
    limits: null
    options: null
    precision: null
    long_name: climate variables for proxy types
    description: The climate variable input to the PSMs for each proxy type - tas by default, except for tree.TRW if Bilinear PSM is utilized (tas + pr)
    data_type: free-form
    complexity: experimental
    URL: null

  ptype_psm_dict:
    value: null
    default: null
    limits: null
    options: null
    precision: null
    long_name: PSM types for proxy types
    description: PSM for each proxy type, Linear by default, and tree.TRW works with both Linear and Bilinear
    data_type: free-form
    complexity: experimental
    URL: null

  ptype_season_dict:
    value: null
    default: null
    limits: null
    options: null
    precision: null
    long_name: seasonality for proxy types
    description: Seasonality configurations for each proxy type
    data_type: free-form
    complexity: experimental
    URL: null

  ptype_forward_dict:
    value: {}
    default: {}
    limits: null
    options: null
    precision: null
    long_name: forward model dictionary
    description: Not used in LMR applications
    data_type: free-form
    complexity: experimental
    URL: null

uncertainty:
  compress_params:
    value: null
    default: null
    limits: null
    options: null
    precision: null
    long_name: compression parameters
    description: Xarray settings to compress the output data
    data_type: free-form
    complexity: advanced
    URL: null
